### ISSUE TITLE
something's wrong with generating image path

### ISSUE THREAD

**Issue by mevsme** [claviska/simple-php-captcha#22] opened 2016-08-04 09:50 UTC
my path is `/media/mvm/Home/Dropbox/Privat/Programming/PHP/site.com/www/vendor/simple-php-captcha-master`

but `$image_src` becomes `/e/Dropbox/Privat/Programming/PHP/site.com/www/vendor/simple-php-captcha-master/simple-php-captcha.php`

**Comment by claviska** [comment] 2016-08-04 15:45
It's using the [realpath](http://php.net/manual/en/function.realpath.php), so that might be what you're seeing.

The image source should be relative to the website root so you can use it in a URL. It shouldn't contain an absolute path, as that wouldn't be very useful to the browser.

**Comment by claviska** [comment] 2017-01-14 16:09
Duplicate of #21

**Closed by claviska** 2017-01-14 16:09 UTC
Labels: Duplicate
